In [73]:
import pandas as pd
import tesiRFX.data_parser as data_parser  # custom module

database = data_parser.create_db("tesiRFX/data")
series_list = [data_dict["time_data"].to_numpy() for data_dict in database]
df = pd.DataFrame(series_list)  # each time series in a separate row

len db with duplicates: 463
len db without duplicates: 239


In [74]:
date_list = [data_dict["date"] for data_dict in database]
type_list = [data_dict["type"] for data_dict in database]
frequency_list = [data_dict["frequency"] for data_dict in database]
exp_time_list = [data_dict["exposure time"] for data_dict in database]
supp_delay_list = [data_dict["supply delay"] for data_dict in database]

# each row is a label of the corresponding column 
labels_df = pd.DataFrame([date_list, type_list, frequency_list, exp_time_list, supp_delay_list]).transpose()
labels_df.head()

0    1      2     3   4
0  22-04-05  DBD  12kHz  180s  1w
1  22-04-05  DBD  12kHz  180s  1w
2  22-04-05  DBD  12kHz  180s  1w
3  22-04-05  DBD  12kHz  180s  1w
4  22-04-05  DBD  12kHz  180s  1w

In [75]:
import tensorflow as tf

ds = tf.data.Dataset.from_tensor_slices(df)

# check correct shapes
dataset_to_numpy = list(ds.as_numpy_iterator())
print(tf.shape(dataset_to_numpy))
print(next(iter(ds)))

tf.Tensor([ 239 1800], shape=(2,), dtype=int32)
tf.Tensor([0.47371767 0.46924816 0.4647164  ... 0.10112904 0.10112929 0.10112953], shape=(1800,), dtype=float64)


In [76]:
ds_labels = tf.data.Dataset.from_tensor_slices(labels_df)

# check correct shapes
dataset_to_numpy = list(ds_labels.as_numpy_iterator())
print(tf.shape(dataset_to_numpy))
print(next(iter(ds_labels)))

tf.Tensor([239   5], shape=(2,), dtype=int32)
tf.Tensor([b'22-04-05' b'DBD' b'12kHz' b'180s' b'1w'], shape=(5,), dtype=string)


In [80]:
tf.data.experimental.save(ds, path="./tesiRFX/features_ds")
tf.data.experimental.save(ds_labels, path="./tesiRFX/labels_ds")

new_dataset = tf.data.experimental.load("./tesiRFX/features_ds")
print(next(iter(new_dataset)))

tf.Tensor([0.47371767 0.46924816 0.4647164  ... 0.10112904 0.10112929 0.10112953], shape=(1800,), dtype=float64)
